---
- name: Deploy Flask app on EC2 instance
  hosts: madden
  become: yes
  tasks:
    - name: Update system packages
      yum:
        name: '*'
        state: latest

    - name: Install dependencies (Python, pip, Flask)
      yum:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Install Flask via pip
      pip:
        name: Flask

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/rum9n/maddenindustries'
        dest: /home/ec2-user/maddenindustries
        force: yes

    - name: Start Flask app
      shell: |
        cd /home/ec2-user/maddenindustries
        export FLASK_APP=app.py
        flask run --host=0.0.0.0 --port=8080
      async: 600
      poll: 0
