---
- name: Install and configure Apache with custom options
  hosts: all
  become: yes

  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Configure Apache to listen on port 8081
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 8081'
        state: present

    - name: Allow port 8081 in the firewall
      ansible.builtin.firewalld:
        port: 8081/tcp
        permanent: yes
        state: enabled

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted

