---
- name: Install Apache with options
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Ensure Apache is installed
      package:
        name: httpd
        state: present

    - name: Enable Apache to start on boot
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Install optional Apache modules
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mod_ssl
        - mod_rewrite
