- name: Test Apache Installation
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Debug service facts
      debug:
        var: ansible_facts.services

    - name: Ensure Apache is running
      assert:
        that:
         

